all:

clean:
	rm -f *~
	cd ClassOriented; make clean
	cd Mixed; make clean
	cd InterfaceOriented; make clean

check:
	cd ClassOriented; make check
	cd Mixed; make check
	cd InterfaceOriented; make check
